# Generated by Django 5.2 on 2025-04-12 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("information", "0004_remove_profilutilisateur_type_de_membre_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ObjetConnecte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("modele", models.CharField(max_length=100)),
                ("type_objet", models.CharField(max_length=100)),
                ("fonction", models.TextField()),
                ("emplacement", models.CharField(max_length=100)),
                ("parametres", models.TextField()),
                ("actif", models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name="profilutilisateur",
            name="role",
            field=models.CharField(
                choices=[
                    ("visiteur", "Visiteur"),
                    ("simple", "Simple"),
                    ("complexe", "Complexe"),
                    ("admin", "Administrateur"),
                ],
                default="visiteur",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="DemandeObjet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_demande",
                    models.CharField(
                        choices=[("ajout", "Ajout"), ("suppression", "Suppression")],
                        max_length=20,
                    ),
                ),
                ("nom", models.CharField(blank=True, max_length=100)),
                ("modele", models.CharField(blank=True, max_length=100)),
                ("type_objet", models.CharField(blank=True, max_length=100)),
                ("fonction", models.TextField(blank=True)),
                ("emplacement", models.CharField(blank=True, max_length=100)),
                ("parametres", models.TextField(blank=True)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "objet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="information.objetconnecte",
                    ),
                ),
            ],
        ),
    ]
